server:
  port: 8084

spring:
  application:
    name: abysshop
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_abysshop?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: jh
    password: 1234
  mvc:
    static-path-pattern: /resources/**
    view:
      suffix: .jsp
      prefix: /WEB-INF/views/